name: pine
description: A lightweight architecture helper for your Flutter projects.
version: 1.0.3
repository: https://github.com/MyLittleSuite/pine
issue_tracker: https://github.com/MyLittleSuite/pine/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter: